name: Generate SoH Archive

on:
  push:
    branches: [ "Custom-Music-2.0" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate SoH archive
      run: |
        cd data
        find . -type f -name '*.ootrs' | while read filename; do unzip -o -d "./Music/`basename -s .ootrs "$filename"`" "$filename"; done;
        wget https://github.com/leggettc18/SequenceOTRizer/releases/download/v0.4/SequenceOTRizer-0.2-Linux.tar.gz
        tar -xzvf SequenceOTRizer-0.2-Linux.tar.gz
        ./SequenceOTRizer --seq-path Music --otr-name daruniasjoy

    - name: Upload generated daruniasjoy.otr
      uses: actions/upload-artifact@v4
      with:
        name: daruniasjoy.otr
        path: data/mods

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: data/mods/daruniasjoy.otr
        tag_name: latest
        name: Ship of Harkinian Bundle
        draft: false
        prerelease: false
